### ISSUE TITLE
Markdown parser broken. Title shown inside code block

### ISSUE THREAD

**Issue by relikd** [toland/qlmarkdown#100]
Markdown isnt rendered properly. Especially tags contained in code blocks should be ignored.
E.g., having this code snippet "some bash script" is rendered as if it where a h1 title.

```
\```
# some bash script
whoami
\```
```

**Comment by setanarut** [comment]
> Markdown isnt rendered properly. Especially tags contained in code blocks should be ignored.
> E.g., having this code snippet "some bash script" is rendered as if it where a h1 title.
> 
> ```
> \```
> # some bash script
> whoami
> \```
> ```

syntax error is caused by you. remove  `\` chars

~~~
```
# some bash script
whoami
```
~~~

**Comment by relikd** [comment]
I've added the backslashes only to show it here in github. Obviously it wasn't necessary as you showed. However, the issue still holds.

![screenshot](https://user-images.githubusercontent.com/1321720/100523649-49fa1d00-31b2-11eb-8d2f-e02b251f1b4d.png)

**Comment by setanarut** [comment]
can you share .md file as  gist.

**Comment by relikd** [comment]
https://gist.github.com/relikd/3f8a28e8ac4ca67676ca2e0f91124bf2

**Comment by relikd** [comment]
Ok, I am not sure what is going wrong. If I download the latest release 1.3.6 (which has a CFBundleShortVersion of 1.3.5), the parser works fine. The above issue only occurs if I compile my own version. Which doesn't even touch any of the preview rendering, only the thumbnail rendering https://github.com/toland/qlmarkdown/pull/95/files.

**Comment by setanarut** [comment]
<img width="834" alt="Ekran Resmi 2020-11-28 22 56 55" src="https://user-images.githubusercontent.com/36481442/100524948-b0406900-31cd-11eb-8176-e9216f643695.png">

homebrew version works fine.

```
➜  ~ brew info qlmarkdown
qlmarkdown: 1.3.6
https://github.com/toland/qlmarkdown
/usr/local/Caskroom/qlmarkdown/1.3.6 (149B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/qlmarkdown.rb
==> Name
QLMarkdown
==> Description
QuickLook generator for Markdown files
==> Artifacts
QLMarkdown.qlgenerator (QuickLook Plugin)
==> Analytics
install: 1,872 (30 days), 5,008 (90 days), 24,925 (365 days)
```

**Comment by setanarut** [comment]
@relikd This project has been abandoned. There is no point in opening a issue here.
