### ISSUE TITLE
GitHub engine and styling?

### ISSUE THREAD

**Issue by kentcdodds** [toland/qlmarkdown#43]
The styling looks a little dated. As many of us ultimately put our markdown files up on GitHub, I would love to see this use the same engine and styling as GitHub for rendering the markdown. Perhaps using @sindresorhus's repo would help with the styling? https://github.com/sindresorhus/github-markdown-css

**Comment by doup** [comment]
:+1:

**Comment by eprev** [comment]
Check this out https://gist.github.com/eprev/625c9a505b238008cfc8

**Comment by kentcdodds** [comment]
Worked for me! Thanks :+1:
