### ISSUE TITLE
How to get to QLMarkdown.qlgenerator

### ISSUE THREAD

**Issue by em14Vito** [toland/qlmarkdown#58]
In the zip file that you offer, I can not find the QLMarkdown.qlgenerator. Should I using Xcode to compile the QLMarkdown.xcodeproj in the Xcode? Thank you very  much!

**Comment by tarwich** [comment]
I just pushed a new release to fix this for you. You can find it at https://github.com/toland/qlmarkdown/releases/tag/v1.3.4

HTH

**Comment by em14Vito** [comment]
I got it. Many thanks!!

**Comment by tarwich** [comment]
No problem! :smile: 
Closing this issue.
