### ISSUE TITLE
Can't install with brew on macOS 10.12.4

### ISSUE THREAD

**Issue by tomsoderlund** [toland/qlmarkdown#80]
I’m trying this on macOS 10.12.4:

	brew update && brew cask install qlmarkdown

But getting this:

	warning: unable to unlink .travis.yml: Permission denied
	warning: unable to unlink .yardopts: Permission denied
	warning: unable to unlink CONTRIBUTING.md: Permission denied
	warning: unable to unlink SUPPORTERS.md: Permission denied
	fatal: cannot create directory at '.github': Permission denied
	Error: Failure while executing: git pull --ff --no-rebase --quiet origin refs/heads/master:refs/remotes/origin/master

Any ideas?

**Comment by tattali** [comment]
That's work for me have you try :
```cd "$(brew --repo)" && git fetch && git reset --hard origin/master && brew update```

**Comment by tomsoderlund** [comment]
Thanks @tattali! My Homebrew installation was broken, I did a reinstall: https://brew.sh

**Comment by tattali** [comment]
You're welcome
