### ISSUE TITLE
How do you run qlmarkdown?

### ISSUE THREAD

**Issue by robertf57** [toland/qlmarkdown#83]
I hate to sound dense but how do you actually **use** this to view a .md file?  I installed it on MacOS 10.12 but there's no executable in /usr/local/Caskroom/qlmarkdown.  And if I right-click a .md file, and select "Open with...", it's not an option.

**Comment by tattali** [comment]
Hi the Quicklook is a software who works when you press the 'space bar'. 
Try to install and uninstall it to prove it.
