### ISSUE TITLE
Auto Dark/Light Mode Switch - Suggestion

### ISSUE THREAD

**Issue by hazarek** [toland/qlmarkdown#92]
I created a new css with dark mode support. you can use and change it if you like.
https://gist.github.com/hazarek/71c3ed9f0cc9024420888e869a3cb2cd

![cap](https://user-images.githubusercontent.com/36481442/68121047-d4247300-ff17-11e9-9869-8c504f41a56c.gif)

**Comment by toland** [comment]
That's awesome.

**Comment by hazarek** [comment]
@toland you should release the optimized version of this css. default css contains unused rows and is not optimized. If you don't mind I can make a pull request when the CSS is ready. (inline html tags in markdown have not been tested.)

https://www.sitepoint.com/optimizing-css-performance/

**Comment by setanarut** [comment]
deprecated

---

new QLMarkdown -> https://github.com/sbarex/QLMarkdown
