### ISSUE TITLE
Does not work under macOS Catalina Version 10.15.4

### ISSUE THREAD

**Issue by ghost** [toland/qlmarkdown#97]
Love your software! Unfortunately it does not run anymore with error "Apple cannot search for malware" (translation from German).

macOS Catalina Version 10.15.4

Stay safe!

**Comment by ghost** [comment]
Strange. After some clicks it is working now.

**Comment by Rabattkarte** [comment]
Still a bug! See attachment (sorry, it's in German). Still the same error message.

<img width="435" alt="Bildschirmfoto 2020-03-31 um 13 34 57" src="https://user-images.githubusercontent.com/16440184/78022065-9e63a900-7354-11ea-958e-1b83f87f6419.png">

I tried uninstalling & force reinstalling via `brew` prior, like this:

```bash
brew update && brew cask uninstall qlmarkdown && brew cask install --force qlmarkdown
```
